-- MySQL Script generated by MySQL Workbench
-- 04/03/16 11:43:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HealthLive`
-- -----------------------------------------------------

-- Note from LeeAnn: This is the first CREATE script for the database. Please let me know of any 
-- problems or changes you want to see addressed. Thanks.

-- -----------------------------------------------------
-- Schema HealthLive`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HealthLive` DEFAULT CHARACTER SET utf8 ;
USE `HealthLive` ;

-- -----------------------------------------------------
-- Table `HealthLive`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`User` (
  `idUser` INT NOT NULL,
  `emailUser` VARCHAR(45) NULL,
  `fnameUser` VARCHAR(45) NOT NULL,
  `lnameUser` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Meal` (
  `calories` INT NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `food//drink` VARCHAR(45) NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`calories`, `amount`, `name`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Diet` (
  `calorieGoal` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`calorieGoal`, `date`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Excercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Excercise` (
  `datetime` DATETIME NOT NULL,
  `nameEx` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `completed` TINYINT(1) NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`datetime`, `nameEx`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Medicine` (
  `name` VARCHAR(45) NOT NULL,
  `frequency` VARCHAR(45) NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `time` DATETIME NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`name`, `frequency`, `duration`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Sleep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Sleep` (
  `duration` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`duration`, `datetime`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthLive`.`Alchoholic drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HealthLive`.`Alchoholic drinks` (
  `amount` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `alcbyvol` VARCHAR(45) NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`amount`, `datetime`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `HealthLive`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
