
-- INSERT script for test user, filling all attributes in all tables

--------------------------------------------------------------------
-- Version History
-- v2B: CREATE script generated by MySQL with fixed FK names
-- WARNING: Script not tested; MySQl had issues with Python modules while attempting to run script
-- v2: Fixed names on foreign keys. All FKs now have unique names
-- v1: Initial version
--------------------------------------------------------------------

--Values for User
INSERT INTO User(idUser,emailUser,fnameUser,lnameUser,password)
VALUES ('111','email@email.com', 'John', 'Doe', 'password')

-- Values for Excercise
-- Note: May need to rename 'datetime' and 'type' attributes in tables if they conflict with keywords
INSERT INTO Excercise(datetime, nameEx, type, completed, idUserEx)
VALUES ('01/01/2001','Cycling', 'Cardio', 'true', '111')

-- Values for Alchoholic drinks
INSERT INTO Alchoholic drinks(amount, datetime, alcbyvol, idUserAlc)
VALUES ('12oz','02/02/2002', '8%', '111')

-- Values for Meal
INSERT INTO Meal(calories, amount, name, type, date, food//drink, idUserMeal)
VALUES ('330','12oz', 'Salmon', 'Fish', '01/01/2001','food','111')

-- Values for Diet
INSERT INTO Diet(calorieGoal, date, idUserDiet)
VALUES (,'1200','01/01/2001','111')

-- Values for Medicine
INSERT INTO Medicine(name, frequency, duration, time, idUserMed)
VALUES ('Claritin','1 per 24h', '2 weeks', '01/01/2001', '111')

-- Values for Sleep
INSERT INTO Sleep(duration,datetime, idUserSleep)
VALUES ('6 hours', '01/01/2001', '111')